# Generated by Django 2.2 on 2021-05-16 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0003_auto_20210516_0532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
    ]
